### ISSUE TITLE
Stuttering cameras

### ISSUE THREAD

**Issue by RobHofmann** [xannor/ha_shinobicctv#5]
Hi there,

First of all: amazing work on this plugin. The setup goes flawelessly smooth. Added 6 cameras from shinobi in mere seconds.

The issue i'm running into is that the camera stream is stuttery. It appears to update "in waves". it stops updating for 1-2 seconds then all the images from those 1-2 seconds will be pushed into ~0,5second before it will restart the same cycle.

Is there any workaround known?

If you need more information, please let me know. The streams from shinobi directly in VLC seem to run fine.

The hardware i'm running on is a Ryzen 3900X machine with 128GB memory. I'm running a VM on top of this (Ubuntu 18.04 LTS) with a Home Assistant Docker & Shinobi Docker.

PS. Which profiles do you use for your camera's?

Kind regards,
Rob

**Comment by xannor** [comment]
Right now the code pulls the list of streams from shinobi, and then if there is no MJPEG stream it will use ffmpeg to convert the primary to MJPEG (as this is the format that it seems HA expects.) For the stills, if the JPEG API is not enabled, again FFMPEG is used to capture stills. Right now I do not have a limiter to how often it will capture so it is possible that having the entity frames up and trying to view a single stream is stuttering because of the other ffmpeg snapshot grabs. 

You could try enabling the JPEG API for each monitor, then restart HA (I dont have a live update process yet) and see if the stutter goes away.

As for my profiles, right now I only have two IP Cams and I am just using hls passthrough, probably not optimal.

**Comment by RobHofmann** [comment]
Alright. So I fixed this. My WiFi points were on a DFS Channel. Apparently not all WiFi devices like this. This is where my issues with stuttering & slow wifi (which i discovered later) came from.

Sorry to have bothered you. I hope someone else can solve this quicker in the future :).
